### ISSUE TITLE
Failed to attach a snapshot/clone volume

### ISSUE THREAD

**Issue by dewongway** [Seagate/seagate-exos-x-csi#61]
**Describe the bug**
Created a snapshot and a PVC based on the snapshot. The pod failed to attach/mount the snapshot volume.

**To Reproduce**
1. Create a VolumeSnapshotClass
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: me5-ext4-snapshotclass
driver: csi-exos-x.seagate.com
deletionPolicy: Delete
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: seagate-exos-x-csi-secrets
  csi.storage.k8s.io/snapshotter-secret-namespace: seagate
  fsType: ext4
  pool: A
  volPrefix: snp  # Prefix for snapshot volumes, an underscore is appended
```

2. Create a snapshot, PVC and a new pod to use the new PV

```
# Take a snapshot of an existing PVC. 
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: me5-vol-templ-seagate-ext4-test-0-snapshot
spec:
  volumeSnapshotClassName: me5-ext4-snapshotclass
  source:
    persistentVolumeClaimName: me5-vol-templ-seagate-ext4-test-0

# Create a new PVC based on the snapshot above
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: me5-vol-templ-seagate-ext4-test-0-clone
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: me5-ext4-storageclass
  dataSource:
    name: me5-vol-templ-seagate-ext4-test-0-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io

# Create a new pod using the snapshot PVC
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-ss
spec:
  containers:
  - image: ghcr.io/seagate/seagate-exos-x-testapp
    name: test-pod-container-ss
    volumeMounts:
    - mountPath: /vol
      name: me5-vol1
  volumes:
  - name: me5-vol1
    persistentVolumeClaim:
      claimName: me5-vol-templ-seagate-ext4-test-0-clone

```

3. The volumesnapshot was created successfully.
```
$ kubectl get volumesnapshot -n seagate-test2
NAME                                         READYTOUSE   SOURCEPVC                           SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS            SNAPSHOTCONTENT                                    CREATIONTIME   AGE
me5-vol-templ-seagate-ext4-test-0-snapshot   true         me5-vol-templ-seagate-ext4-test-0                           50Mi          me5-ext4-snapshotclass   snapcontent-0ac045a0-721a-463d-aacb-488bd30c867d   8h             138m
```

4. The PVC and PV were created successfully.
```
$ kubectl get pvc -n seagate-test2
NAME                                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS            AGE
me5-vol-templ-seagate-ext4-test-0         Bound    pvc-32d7075d-4098-4a93-b2fc-ab9526f001a3   25Gi       RWO            me5-ext4-storageclass   20h
me5-vol-templ-seagate-ext4-test-0-clone   Bound    pvc-9ff78e4b-aab9-42b1-9166-3503c73dd254   25Gi       RWO            me5-ext4-storageclass   138m
me5-vol-templ-seagate-ext4-test-1         Bound    pvc-59f5e160-543c-450a-947f-619a6f0d9329   25Gi       RWO            me5-ext4-storageclass   20h

$ kubectl get pv -n seagate-test2
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                   STORAGECLASS                 REASON   AGE
pvc-32d7075d-4098-4a93-b2fc-ab9526f001a3   25Gi       RWO            Delete           Bound    seagate-test2/me5-vol-templ-seagate-ext4-test-0         me5-ext4-storageclass                 20h
pvc-59f5e160-543c-450a-947f-619a6f0d9329   25Gi       RWO            Delete           Bound    seagate-test2/me5-vol-templ-seagate-ext4-test-1         me5-ext4-storageclass                 20h
pvc-9ff78e4b-aab9-42b1-9166-3503c73dd254   25Gi       RWO            Delete           Bound    seagate-test2/me5-vol-templ-seagate-ext4-test-0-clone   me5-ext4-storageclass                 140m
pvc-b5b16493-ff69-4581-9016-c02c7767d287   35Gi       RWO            Delete           Bound    seagate-test/me5-vol-templ-seagate-xfs-test-1           me5-xfs-storageclass                  20h
pvc-d4032606-a522-4b62-9647-9f985116163b   35Gi       RWO            Delete           Bound    seagate-test/me5-vol-templ-seagate-xfs-test-0           me5-xfs-storageclass                  20h

```

5. The new pod failed at AttachVolume.Attach.
```
$ kubectl describe pod test-pod-ss -n seagate-test2
Name:             test-pod-ss
Namespace:        seagate-test2
Priority:         0
Service Account:  default
Node:             test-cluster-pool1-7404b9af-zht6b/100.88.159.134
Start Time:       Thu, 02 Feb 2023 11:09:51 -0600
Labels:           objectset.rio.cattle.io/hash=14c05b12854f5afe430e3664fa0eabeaa3de697f
Annotations:      kubernetes.io/psp: global-unrestricted-psp
                  objectset.rio.cattle.io/applied:
                    H4sIAAAAAAAA/3yRvY7bMBCE32Vr0acfSudTmzrBVdcELlbk0mbCP4hrwYChdw8oxTGSAFdpRc58OwPeAZP9oDnbGGCEpYEKftqgYYT3qKECT4waGWG8A4YQGdnGkMtvnH6Q4kx8mG...
                  objectset.rio.cattle.io/id: 42ef2d92-7a86-4f21-a65d-d4ff5c186d3e
Status:           Pending
IP:               
IPs:              <none>
Containers:
  test-pod-container-ss:
    Container ID:   
    Image:          ghcr.io/seagate/seagate-exos-x-testapp
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dwknj (ro)
      /vol from me5-vol1 (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  me5-vol1:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  me5-vol-templ-seagate-ext4-test-0-clone
    ReadOnly:   false
  kube-api-access-dwknj:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason              Age                    From                     Message
  ----     ------              ----                   ----                     -------
  Warning  FailedMount         9m27s (x11 over 138m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[me5-vol1], unattached volumes=[kube-api-access-dwknj me5-vol1]: timed out waiting for the condition
  Warning  FailedAttachVolume  110s (x77 over 142m)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-9ff78e4b-aab9-42b1-9166-3503c73dd254" : rpc error: code = NotFound desc = The specified volume (csi_8e4baab942b191663503c73dd254) was not found.
  Warning  FailedMount         25s (x52 over 140m)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[me5-vol1], unattached volumes=[me5-vol1 kube-api-access-dwknj]: timed out waiting for the condition
```

6. On the storage array, I can see, the volume was created but not mapped/attached to the node.

![image](https://user-images.githubusercontent.com/27778629/216432795-3b64139c-45c4-4964-9441-1e15fcb94132.png)

**Expected behavior**
The pod should be able to find the volume and attach/mount on the node automatically. 

**Storage System (please complete the following information):**
	 - Vendor: Dell PowerVault ME5
	 - Model: ME5024
	 - Firmware Version: ME5.1.0.1.0

**Environment:**
	- Kubernetes version: v1.24.4+rke2r1
	- Host OS: SUSE Linux Enterprise Server 15 SP3

**Additional context**
